fix: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN (#360)

diff --git a/.github/actions/update-gitops/action.yml b/.github/actions/update-gitops/action.yml
--- a/.github/actions/update-gitops/action.yml
+++ b/.github/actions/update-gitops/action.yml
@@ -24,10 +24,21 @@ inputs:
   BRANCH_NAME:
     required: false
     description: The branch name to create if CREATE_PR is true.
+  GH_TOKEN:
+    required: false
+    description: GitHub Token for authentication
 
 runs:
   using: "composite"
   steps:
+    - name: Validate inputs
+      run: |
+        if [ "${{ inputs.CREATE_PR }}" == "true" ] && [ -z "${{ inputs.GH_TOKEN }}" ]; then
+          echo "GH_TOKEN is required when CREATE_PR is true."
+          exit 1
+        fi
+      shell: bash
+
     - name: Checkout GitOps repo
       uses: actions/checkout@v4
       with:
@@ -106,6 +117,8 @@ runs:
       shell: bash
       if: inputs.CREATE_PR == 'true'
       working-directory: gitops
+      env:
+        GH_TOKEN: ${{ inputs.GH_TOKEN }}
       run: |
           git push -u origin "$BRANCH_NAME"
           gh pr create --title "Update image tag for ${{ inputs.SERVICE_NAME }}" --body "Update image tag for ${{ inputs.SERVICE_NAME }}"
